# 非常停止ボタン解除
string TRIGGER_EMERGENCY_BUTTON_OFF = emergency_button_off
# 非常停止ボタン押下
string TRIGGER_EMERGENCY_BUTTON_ON = emergency_button_on
# カルガモボタン押下
string TRIGGER_KARUGAMO_BUTTON_ON = karugamo_button_on
# リモコン:カルガモボタン押下
string TRIGGER_REMOTE_KARUGAMO_BUTTON_ON = remote_karuamo_button_on
# リモコン:マニュアルボタン押下
string TRIGGER_REMOTE_MANUAL_BUTTON_ON = remote_manual_button_on
# リモコン:アイドルボタン押下
string TRIGGER_REMOTE_IDLE_BUTTON_ON = remote_idle_button_on
# アイドルボタン押下
string TRIGGER_IDLE_BUTTON_ON = idle_button_on
# 進行方向 2000 mm 以内に障害物を発見
string TRIGGER_DETECT_OBSTACLE = detect_obstacle
# 前方近傍に障害物を発見（LIDAR進行方向 500 mm以内）
string TRIGGER_DETECT_DANGER_OBSTACLE = detect_danger_obstacle
# ガードバンパー接触
string TRIGGER_COLLISION = collision
# ブレーキ解除ボタン押下
string TRIGGER_BREAK_RELEASE_BUTTON_ON = break_release_button_on
# 対象ロストから10秒経過
string TRIGGER_LONG_LOST = long_lost

string trigger
